# Exercise 2: Identify the Principal Component from Loading Table

Given a loading table of 9 variables on 3 principal components, identify which variable dominates each component and determine the overall principal component.

In [ ]:
# Name: B Lohith Krishnan
# Roll Number: CH.SC.U4CSE24153

import pandas as pd
import numpy as np

## Recreate Loading Table

In [2]:
data = {
    'Variable': ['Climate', 'Housing', 'Health', 'Crime', 'Transportation',
                 'Education', 'Arts', 'Recreation', 'Economy'],
    'PC1': [0.190, 0.544, 0.782, 0.365, 0.585, 0.394, 0.985, 0.520, 0.142],
    'PC2': [0.017, 0.020, 0.605, 0.294, 0.085, 0.273, 0.126, 0.402, 0.150],
    'PC3': [0.207, 0.204, 0.148, 0.585, 0.234, 0.027, 0.000, 0.519, 0.239]
}

df = pd.DataFrame(data)
df = df.set_index('Variable')
print(df)

                  PC1    PC2    PC3
Variable                           
Climate         0.190  0.017  0.207
Housing         0.544  0.020  0.204
Health          0.782  0.605  0.148
Crime           0.365  0.294  0.585
Transportation  0.585  0.085  0.234
Education       0.394  0.273  0.027
Arts            0.985  0.126  0.000
Recreation      0.520  0.402  0.519
Economy         0.142  0.150  0.239


## Find Dominant Component for Each Variable

In [3]:
for var in df.index:
    row = df.loc[var]
    pc = row.idxmax()
    val = row.max()
    print(f'{var:15s} -> {pc} (loading = {val:.3f})')

Climate         -> PC3 (loading = 0.207)
Housing         -> PC1 (loading = 0.544)
Health          -> PC1 (loading = 0.782)
Crime           -> PC3 (loading = 0.585)
Transportation  -> PC1 (loading = 0.585)
Education       -> PC1 (loading = 0.394)
Arts            -> PC1 (loading = 0.985)
Recreation      -> PC1 (loading = 0.520)
Economy         -> PC3 (loading = 0.239)


## Find Dominant Variable for Each Component

In [4]:
print('\nDominant variable per component:')
print('-' * 40)
for pc in ['PC1', 'PC2', 'PC3']:
    idx = df[pc].idxmax()
    val = df[pc].max()
    print(f'{pc}: {idx} (loading = {val:.3f})')


Dominant variable per component:
----------------------------------------
PC1: Arts (loading = 0.985)
PC2: Health (loading = 0.605)
PC3: Crime (loading = 0.585)


## Conclusion

The **principal component** is the component that captures the most variance, which is dominated by the variable with the highest loading.

- **PC1** is dominated by **Arts** (loading = 0.985) - the highest overall loading
- **PC2** is dominated by **Health** (loading = 0.605)
- **PC3** is dominated by **Crime** (loading = 0.585)

Since Arts has the highest absolute loading (0.985) on PC1, and PC1 typically captures the most variance, the principal component is **PC1** with Arts as the dominant variable.